dest_folder = "./data"
dataset_id = "austin_crime"
table_id = "crime"
finished_workflow = "false"
postgres_host = "35.188.22.29"
postgres_database = "austin-crime-db"
postgres_user = "postgres"
postgres_password = "12345678"
postgres_port = "5432"
api_url = "https://data.austintexas.gov/resource/fdj4-gpfu.json?$order=occ_date_time DESC"